//======================================== 逻辑 ========================================
// 我们可以先看一下package.json 的 script
  // "dev": "node server", //"dev注释":"本地测试服务",
  // "start": "cross-env NODE_ENV=production node server",//"本地测试生产服务",
  // "build": "rimraf dist && npm run build:client && npm run build:server",//"编译",
// 再结合官网的那张图
  // https://ssr.vuejs.org/zh/guide/structure.html#%E4%BB%8B%E7%BB%8D%E6%9E%84%E5%BB%BA%E6%AD%A5%E9%AA%A4
  // https://cloud.githubusercontent.com/assets/499550/17607895/786a415a-5fee-11e6-9c11-45a2cfdf085c.png
// 总体流程就是
  // 通过webpack 两个入口文件 打包出两个 bundle 一个是被服务处理过的首页预渲染  另一个是正常的前端js
  // 浏览器第一次打开的时候得到的是预渲染的页面 后面的处理就是正常的vue逻辑
// scripts 中有两种逻辑
  // 一种是正常的根据双入口打包
  // 另一种是通过同一个 setup-dev-server 引入带有环境变量的双入口

// server.js 是一个express
// build/setup-dev-server.js 是一个webpack-dev-server
// build/webpack.client.config.js 
// build/webpack.server.config.js  排除掉node  不包含document  Commonjs 
// src/entry-client  客户端入口 正常js
// src/entry-server  服务器入口 导出Vue实例

//======================================== 这是 express 的服务 ========================================
const fs = require('fs')
const path = require('path')
const LRU = require('lru-cache') // 缓存库 http://skyhigh233.com/blog/2016/10/07/lru-cache/
const express = require('express')
const favicon = require('serve-favicon')
const compression = require('compression') // 压缩库
const microcache = require('route-cache') // 路由缓存 一般来说不使用 因为这是ssr项目 不需要不断地计算 所以才有用
const resolve = file => path.resolve(__dirname, file) // 获取绝对路径
const { createBundleRenderer } = require('vue-server-renderer')

const isProd = process.env.NODE_ENV === 'production' // 是否生产环境
const useMicroCache = process.env.MICRO_CACHE !== 'false' // 是否使用路由缓存
const serverInfo =
  `express/${require('express/package.json').version} ` +
  `vue-server-renderer/${require('vue-server-renderer/package.json').version}`

const app = express() 

function createRenderer (bundle, options) { // 以默认参数为主 合并 传入的options
  // https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/README.md#why-use-bundlerenderer
  return createBundleRenderer(bundle, Object.assign(options, {
    // for component caching
    cache: LRU({ // 缓存组件的配置
      max: 1000,
      maxAge: 1000 * 60 * 15
    }),
    // this is only needed when vue-server-renderer is npm-linked
    basedir: resolve('./dist'),
    // recommended for performance
    runInNewContext: false
  }))
}

let renderer // 渲染用
let readyPromise // 这里先声明一下  在开发环境的时候要使用

const templatePath = resolve('./src/index.template.html') // 获得模板文件路径
if (isProd) {
  //======================================== 生产环境 ========================================  
  // In production: create server renderer using template and built server bundle.
  // The server bundle is generated by vue-ssr-webpack-plugin.
  const template = fs.readFileSync(templatePath, 'utf-8') // 读取模板
  const bundle = require('./dist/vue-ssr-server-bundle.json') // 得到webpack 编译后的文件
  // The client manifests are optional, but it allows the renderer
  // to automatically infer preload/prefetch links and directly add <script>
  // tags for any async chunks used during render, avoiding waterfall requests.
  const clientManifest = require('./dist/vue-ssr-client-manifest.json') // 
  renderer = createRenderer(bundle, { // 这里的编译只走一遍(编译全部)
    template,
    clientManifest
  })
} else {
  //======================================== 开发环境 ========================================
  // In development: setup the dev server with watch and hot-reload,
  // and create a new renderer on bundle / index template update.
  readyPromise = require('./build/setup-dev-server')(
    app,
    templatePath,// 这里没有采用前端的 html-webpack-plugin 而是使用传入模版路径通过fs读取文件后 createRenderer 自动生成html
    (bundle, options) => { // 这里的编译是给热更新用的  传给热更新服务器  不断地触发热更新
      renderer = createRenderer(bundle, options)
    }
  )
}
//---------------------------------------- 下面是正常的服务器接口 ----------------------------------------

const serve = (path, cache) => express.static(resolve(path), {  // 修改暴露静态文件的方法  第二个参数是 设置最长时效
  maxAge: cache && isProd ? 1000 * 60 * 60 * 24 * 30 : 0
})

app.use(compression({ threshold: 0 }))
app.use(favicon('./public/logo-48.png'))
app.use('/dist', serve('./dist', true))
app.use('/public', serve('./public', true))
app.use('/manifest.json', serve('./manifest.json', true))
app.use('/service-worker.js', serve('./dist/service-worker.js')) // 暴露service-worker 这个文件好像是拦截服务器请求的 网络代理服务器

// since this app has no user-specific content, every page is micro-cacheable.
// if your app involves user-specific content, you need to implement custom
// logic to determine whether a request is cacheable based on its url and
// headers.
// 1-second microcache.
// https://www.nginx.com/blog/benefits-of-microcaching-nginx/
app.use(microcache.cacheSeconds(1, req => useMicroCache && req.originalUrl)) // 所有的东西都设置缓存1秒

function render (req, res) {
  const s = Date.now()

  res.setHeader("Content-Type", "text/html")
  res.setHeader("Server", serverInfo)

  const handleError = err => {
    if (err.url) {
      res.redirect(err.url)
    } else if(err.code === 404) {
      res.status(404).send('404 | Page Not Found')
    } else {
      // Render Error Page or Redirect
      res.status(500).send('500 | Internal Server Error')
      console.error(`error during render : ${req.url}`)
      console.error(err.stack)
    }
  }

  const context = {
    title: 'Vue HN 2.0', // default title
    url: req.url
  }
  renderer.renderToString(context, (err, html) => { // 渲染
    if (err) {
      return handleError(err)
    }
    res.send(html)
    if (!isProd) {
      console.log(`whole request: ${Date.now() - s}ms`)
    }
  })
}

app.get('*', isProd ? render : (req, res) => { // 处理所有的get请求
  readyPromise.then(() => render(req, res))// 这里之所以用promise 来写开发环境 是为了提取出dev-server
})

const port = process.env.PORT || 8081
app.listen(port, () => { // 启动服务器
  console.log(`server started at localhost:${port}`)
})
